### ISSUE TITLE
[IDEA] Hacer la base de datos pública 

### ISSUE THREAD

**Issue by barreeeiroo** [duhow/ProfesorOak#105]
Hacer un usuario con phpMyAdmin en tu base de datos que sólo pueda leer y escribir en la base de datos del bot, para así que todos los bots tengan una base de datos común

**Comment by duhow** [comment]
NOPE. Eso es REST API, y de momento no se hará... De momento.
Tampoco es plan de que haya 50.000 Profesor Oak, si no aquí se lia la madre con datos dispersos por todos lados...
