### ISSUE TITLE
Como interaccionar con el bot?

### ISSUE THREAD

**Issue by lluisd** [duhow/ProfesorOak#106]
Si escribo palabras como:
profe
añadir pokeparadas

el bot no dice ni hace nada.

Es la primera vez que utilizo un bot en telegram. Me he leido el README de este proyecto pero no especifica ninguno de sus comandos, los he visto mirando el codigo por encima pero aun asi algo hago mal. Podrias porfavor explicar los comandos-palabras que puedes enviar al bot en el README? La idea es muy buena pero un poco de info iria bien para los principiantes como yo y mucha gente.

**Comment by SKillusion** [comment]
Hablale a bot y escribe "Oak ayuda", te mandará un mensaje con algunas de sus funciones. El bot esta aún en desarrollo, muchas funciones no están terminadas o no han llegado a su forma final por lo cuál documentarlo ahora mismo no tiene mucho sentido...
