### ISSUE TITLE
Instalación del bot en el README.md

### ISSUE THREAD

**Issue by barreeeiroo** [duhow/ProfesorOak#108]
Añadir al README.md un apartado para la instalación o cosas así
Si quieres ya me encargo yo. Asígname el issue para q me acuerde.

Y algo opcional sería hacer una wiki (wiki.github.com/duhow/ProfesorOak) con muchos datos acerca del bot: instalación, comandos, contribuidores, licencia, etc.

**Comment by SKillusion** [comment]
Como ha comentado @duhow en varias ocasiones es mejor que no todo el mundo sepa instalar Oak. Para la mayoría de las contribuciones no hace falta (el código se puede probar perfectamente sin el bot) y a los que realmente les haga falta el bot sabrán como instalarlo.
Documentar los comandos es buena idea, aunque no se si es necesario crear una wiki entera para ello o simplemente bastaría con usar un archivo en Markdown...
Acerca de los contribuidores: tenemos los gráficos de Github (podríamos mencionar a los más importantes en el README...
Licencia... la verdad es que es hora de elegir una :sweat_smile:

**Comment by barreeeiroo** [comment]
@SKillusion La licencia puede ser GNU

**Comment by marcroga** [comment]
@SKillusion me gustaría contactar contigo por Telegram 

User: /Pikaping

Saludos
