### ISSUE TITLE
[IDEA] Registro de "no lectura"

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#115]
La gente no lee. Y como no lee, no sigue la sintaxis correspondiente al registro, así que hay que hacer dos cambios importantes:

- [ ] Si dice un color suelto (rojo, azul o amarillo), validar. Sólo una palabra. Esto será una función aparte a la que ya hay.
- [ ] En el momento de decir el color, activar un STEP de un sólo uso. Si dice una única palabra, tomar esa palabra como nombre de usuario. Y tanto si es una palabra como varias, anular ese STEP independientemente del resultado.

**Comment by barreeeiroo** [comment]
Pero eso no podría entrar en conflicto con una conversación normal? Es decir, alguien está hablando y dice un color, que pasa?
Y lo mismo para el nombre: escribe una palabra sin querer o el corrector se la corrige y con acto reflejo le da a enviar (a mi me ha pasado, xD) y no puede hacer nada

**Comment by duhow** [comment]
Eso es ser gafe. Muy gafe. Si te pregunta el Oak, al menos ten el "respeto" de responderle... Igualmente el proceso está pensado para ser continuo, así que me aseguro que al menos el 80% de los casos no habrá problemas, y me aseguro los registros :)

**Comment by barreeeiroo** [comment]
👍
