### ISSUE TITLE
[BUG] Debilidad de doble tipo se contradice

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#13]
No le afecta fuego y le afecta mucho fuego.
Comprobar el efecto final y cómo se queda al final.

**Comment by RussianEngineer** [comment]
Crea dos variables int, ponles de valor default 0. Cada una de estas variables hara referencia a si es muy o poco eficaz. Imaginate que tienes un pokemon planta y agua y le atacas con fuego. Fuego a planta es muy eficaz, a la primera variable le asignas de valor 2. Pero fuego a agua no es muy eficaz asi que a la segunda variable le asignas el valor 1. (0 = daño normal, 1 = no es muy eficaz, 2 = es muy eficaz.)
Si las dos variables son 2 dira: es super eficaz (x1.5), si las dos son 1 o una es 1 y la otra es 0 dira que no es muy eficaz (x0.8), si una es 0 y la otra dos dira que es muy eficaz (x1.25), si las dos son 0 no dira nada y si una es 2 y la otra es 1 tampoco dira nada :) 
Espero que lo entiendas

**Comment by SKillusion** [comment]
Si [esto](http://www.pokemongodb.net/2016/05/super-effective.html) es correcto, no existe la doble efectividad.
