### ISSUE TITLE
[IDEA] SQL desde el bot

### ISSUE THREAD

**Issue by barreeeiroo** [duhow/ProfesorOak#132]
Hacer un comando para los admins del bot (osea @duhow) tipo /sql, que lo que siga a continuación se ejecute en la base de datos

**Comment by duhow** [comment]
Lol. Y eso para que fin? Aunque pueda usarlo yo, pero... Arriesgado.

**Comment by barreeeiroo** [comment]
Para, por ejemplo, eliminar usuarios sin entrar a la base de datos, o mirar
los datos del usuario

2016-09-02 12:31 GMT+02:00 duhow <notifications@github.com>:
