### ISSUE TITLE
[IDEA] Reportar spam

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#17]
Si mucha gente marca el mensaje con reply /spam , reportar ID mensaje. A extender utilidad.

**Comment by Rapejim** [comment]
Te refieres a marcar como Spam un mensajes que alguien haya escrito?

Y para que serviría eso, para borrarlo si Oak es admin del grupo?
O para algo mas?

**Comment by duhow** [comment]
Por desgracia, ningún bot puede borrar mensajes... aún.
Cuando pueda, podrá borrarlos. De momento es para avisar a los @admin para borrar o hacer flag de users.
