### ISSUE TITLE
Organización y optimización del código de OAK

### ISSUE THREAD

**Issue by Almamu** [duhow/ProfesorOak#177]
La gran mayoría del código de Oak actualmente está dentro de un pedazo de controlador de 154KB de código, esto es insostenible a menos que te conozcas bastante bien el código. Sería recomendable optimizar y re-estructurar la gran mayoría del código para que quede más ordenado y accesible. He creado una rama en mi repo propio para este trabajo, iré haciendo ahí los cambios y proponiendo ajustes aquí y allá: https://github.com/Almamu/ProfesorOak/tree/general-optimization

**Comment by duhow** [comment]
Adoptado el método de plugins gracias a tu idea <3
