### ISSUE TITLE
[IDEA] Página de calculo IV

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#19]
Cuando la gente pregunte como:

- Cómo calculo los IV de un Pokemon?

Responder con la página o servicio adecuado.

**Comment by RussianEngineer** [comment]
Tambien podriamos crear una base de datos con todos los multiplicadores de evolucion asi si alguien pregunta: tengo un Eevee 420 CP a cuanto evolucionara... Y que el respondiera

**Comment by duhow** [comment]
Si se puede implementar la función o pedirla a través de una API, mejor que mejor!

**Comment by duhow** [comment]
Integrar con #64.

**Comment by Rapejim** [comment]
Y si mientras se integra con las respuestas o con el código del profe, el bot responda con la siguiente "herramienta/web"??:
 https://pokeassistant.com/main/ivcalculator
