### ISSUE TITLE
Modificar comportamiento para detección de "topos"

### ISSUE THREAD

**Issue by zamuro** [duhow/ProfesorOak#216]
Modificar la acción del autokick a usuarios de equipos distintos al del grupo de color vinculado. Actualmente es kick, se sugiere cambio a ban.

**Comment by duhow** [comment]
@zamuro Cuando kickea, Telegram no siempre avisa del estado de kick, entonces el usuario vuelve a entrar y no da el aviso de "new_member_chat" a nadie, con lo que parece que no haya hecho nada.

Solución es hacer un ban temporal de 1 minuto, desarrollar plugin correspondiente.
