### ISSUE TITLE
[IDEA] Lista de ataques

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#23]
La función va dividida en varios apartados:
- Lista SQL de todos los ataques, con su correspondiente tipo, fuerza y energía necesaria.
- Lista SQL que asocie los Pokemon con los ataques que puede aprender
- Desarrollar el funcionamiento y mostrar la información

La consulta sería del tipo:
- Ataques de tipo fuego
- Ataque placaje

**Comment by duhow** [comment]
@Leirlux sigo esperando la lista :cry:

**Comment by Leirlux** [comment]
@Duhow ¡Que no se me olvida, tranquilo! Deja que vuelva a *mi casa* en
Madrid; llevo sin pasar desde el lunes. 😂

Saludos cordiales / Kind regards,


*Jesús Moreno Ramos (*aka '*Leirlux*'*)*

2016-08-11 11:44 GMT+02:00 duhow <notifications@github.com>:
