### ISSUE TITLE
[IDEA] Pokédadas

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#24]
Reconocer el texto, interpretando los valores:
- Hora de quedada (o dia - mañana/hoy/ el martes)
- Lugar de quedada (más cercano según la ubicación actual del jugador)
- Si es privado o no (exclusivo color o público)
- Anunciar públicamente a gente cercana o no

Ejemplo: "Quedamos hoy a la tarde en Plaza Cataluya?"

**Comment by duhow** [comment]
Necesario implementar #25 primero.

**Comment by duhow** [comment]
A ver señores, lista de frases que pueda decir la gente para poder hacer búsquedas?

**Comment by RussianEngineer** [comment]
Oak, vamos a quedar en tal sitio a tal hora, no tiene restriccion de color, el bot se lo guarda y simplemente dice: Entrenadores, vamos a quedar en tal sitio a tal hora...
