### ISSUE TITLE
[IDEA] Ranking de conquista de GYMs por equipos 

### ISSUE THREAD

**Issue by Radigar** [duhow/ProfesorOak#26]
Estaría bien un comando en el que Oak pudiera mostrar en tiempo real, con filtrado por zonas opcional, un contador de cuantos gyms están en posesión de que equipo en ese momento, ejemplo:

User--> Oak, ¿quien va ganando (en XXX)?
Oak -> Equipo YYY con ZZZ Gyms (en XXX)

User--> Oak, Ranking global (en XXX)
Oak --> 
Ranking (en XXX)
1° Equipo YYY con ZZZ Gyms
2° Equipo YYY con ZZZ Gyms
3° Equipo YYY con ZZZ Gyms

O también establecerlo mediante porcentajes.

**Comment by barreeeiroo** [comment]
Se de un bot que ya hace esto, pero a nivel de una ciudad. Podría hablar con el y comentarle este proyecto. @duhow

**Comment by duhow** [comment]
Se puede implementar tabla propia de conquistas. Abro nueva...
