### ISSUE TITLE
[IDEA] Shark Attack

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#265]
- [ ] Hacer un **setting** con el mismo nombre, usando el **dia**.
- [ ] Si la persona habla, tiene el setting y el día es distinto, actualizar el día y enviar el audio de [Shark Attack](https://www.youtube.com/watch?v=vihnAK114N8).

> Idea por @l-cafe.

**Comment by L-Cafe** [comment]
masuno
