### ISSUE TITLE
Nidos en grupos

### ISSUE THREAD

**Issue by Boldrimm** [duhow/ProfesorOak#275]
Saludos. 

Creé un grupo donde ya somos 20 personas. El caso es que sólo a mí (admin del grupo) me deja registrar nidos de pokémon. Nadie más lo puede hacer. 
También me encuentro con que yo ni nadie puede eliminar los nidos.

**Comment by duhow** [comment]
Puedes `borrar mis nidos` o `borrar nido de Pikachu en Parque Central`, los demás quedan reservados de momento. Estoy replanteando cómo mejorar la función para los futuros nidos, tema trols y demás. Confírmame que te funciona y cierro problema.

**Comment by Boldrimm** [comment]
Solucionado. Todos los miembros pueden añadir y eliminar nidos
