### ISSUE TITLE
Borrado de mensajes "administrativos"

### ISSUE THREAD

**Issue by JoseLSegura** [duhow/ProfesorOak#304]
El Profesor podría borrar los mensajes administrativos que se mandan a un grupo o supergrupo una vez los haya procesado, siempre y cuando esté añadido como administrador.

Por ejemplo lo veo muy interesante en grupos para gestión de incursiones, donde hay que borrar manualmente el mensaje de creación del raid y aparece "duplicado" (mensaje de "Crear Raid" y mensaje con los botones del Profesor)

**Comment by duhow** [comment]
Se admiten PR. :)
