### ISSUE TITLE
No puedo añadir al profesor a un grupo

### ISSUE THREAD

**Issue by PacoGurney** [duhow/ProfesorOak#307]
Hola! No se si este es el lugar indicado, pero no he encontrado otro sitio donde hacer la pregunta.
Me he registrado con el profesor y lo he invitado a un grupo que estoy creando para mi pueblo. Cuando lo invito, entra al grupo, dice "Nope" y se va.
Así que no tengo manera de incluirlo en el grupo. Nos interesaba mucho para organizar los raids.

¿Alguien sabe qué puede estar pasando? ¿Estoy haciendo algo mal?

Gracias!!

**Comment by duhow** [comment]
Poca gente.

**Comment by PacoGurney** [comment]
Entonces primero hay que llenar el grupo? Pensábamos probar primero, pero
si es así no problem. Somos unos 150 ahora mismo
