### ISSUE TITLE
Ubicacion del grupo

### ISSUE THREAD

**Issue by rafaeljimenez85** [duhow/ProfesorOak#308]
He visto que al intentar registrar la ubicacion del grupo con /set location, Oak detecta la configuracion y devuelve el mapa, pero al preguntarle por la ubicacion del grupo, no reporta la correcta.

Adjunto ejemplo:
![photo5809676517997914839](https://user-images.githubusercontent.com/17180881/29385180-0cec2d14-82d7-11e7-85b9-9f36c61d36ee.jpg)

**Comment by duhow** [comment]
No aplica, y la ubicación del grupo no se puede consultar de momento. Está pensada para un uso en el futuro.
