### ISSUE TITLE
[IDEA] Conquista de gimnasios

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#31]
En base a la ubicación actual, poder reportar que el gimnasio está conquistado por un equipo.

Ejemplo: He capturado el gimnasio Dragón Escarlata! 
(Buscar coincidencias en nombre y ubicación cercana - casa, y cambiar estado de gimnasio).

Si hay API  con DB grande, será preferente usarla.

**Comment by Rapejim** [comment]
Uff, hay gimnasios que cambian de equipo muy rápidamente... puede dar lugar a "falsos positivos" de que equipo tiene que gimnasios.
Yo tengo un a 50m de casa que lo he visto de mi color y con un hueco para meter un pokemon y en lo que he tardado en cambiarme (ponerme pantalo y camiseta) y bajar ya estaba cambiado de color... ¬¬

Podría ayudar el incluir en la informacion un factor como el tiempo que hace desde esa información.
- Hace 5min que un entrenador lo indicó como Azul
o
- Hace 2 días que un entrenador lo indicó como Rojo.
