### ISSUE TITLE
Fallo en solicitud de grupo color

### ISSUE THREAD

**Issue by rafaeljimenez85** [duhow/ProfesorOak#314]
Hola.

Hemos detectado que al solicitar el link del grupo [color], oak envia un privado con el siguiente texto:

Te invito al grupo *Amarillo* asociado a Pokémon go Getafe. ¡No le pases este enlace a nadie!

Pero no envia el enlace, Confirmado en los grupos de Getafe y Vigo.

Un saludo

**Comment by duhow** [comment]
El commit c7a30d0d1acb54a48b9307c0aeed42af6cc25f9f debería arreglar el problema ya.
