### ISSUE TITLE
Restringir consulta de nidos no permite 

### ISSUE THREAD

**Issue by gulfuroth** [duhow/ProfesorOak#326]
Tenemos un grupo en el que ni los admins pueden consultar la lista de nidos completa. 
Lleva a situaciones absurdas como dar de alta un nido mal, querer consultarlo  y que no te deje.  También bloquea a veces el borrado (esto no lo reproduzco el 100%) 

Captura: 
https://www.dropbox.com/s/8jb8hw9y9wp3j07/Screenshot%202017-10-06%2010.55.41.png?dl=0 

Duda/petición: Es posible desactivarlo o modificar los umbrales requeridos?

**Comment by duhow** [comment]
No, **de momento** no es posible.
