### ISSUE TITLE
Faltan instrucciones para desplegar el bot

### ISSUE THREAD

**Issue by gentakojima** [duhow/ProfesorOak#335]
Estaría bien mientras no tienes Oak 2.0 que hubiera instrucciones para desplegar el bot con el objetivo de poder hacer pull requests en condiciones, probando las cosas antes. Hay pequeñísimas mejoras que se porían hacer en base a cositas que nos pasan cada día en el grupo de ayuda y oye, nunca me animo a enviarte nada porque como no puedo probarlo, voy un poco a ciegas.

**Comment by duhow** [comment]
Aun yendo a ciegas, el código no necesita demasiado testeo, y en cualquier caso siempre se pueden hacer pruebas y commits hasta finalmente llegar a hacer el commit adecuado.
Si tienes cualquier idea o lo que sea, eres libre de hacer PRs :)
Aunque preferiría que fuesen directamente sobre la nueva branch, no pretendo hacer más cambios en la master.
