### ISSUE TITLE
Imagen de Shinies disponibles

### ISSUE THREAD

**Issue by Nickycita** [duhow/ProfesorOak#336]
AgADBAADhKsxG2l-2VORkrpsJDz7Mhu-4RkABM9ClXHxnic-oRMEAAEC

Por si lo quieres poner, saludines :3 (no se usar esto xD)

**Comment by duhow** [comment]
Pokemon_info.php 

Crea un nuevo comando que sea algo como ("lista de", ["shiny", "shinies", "varicolor", "varicolores"]) y que envíe la foto.
