### ISSUE TITLE
¿Como conocer a los usuarios del canal?

### ISSUE THREAD

**Issue by Cofyman** [duhow/ProfesorOak#338]
Hola, quería saber si existe (o se podría hacer) un comando que te diera un listado completo de todos los usuarios de un canal parecido al listado que aparece cuando alguien se apunta a una raid y así saber quien le falta poner el color, el nivel o validarse. Este mensaje le llegaría al admin del canal que lo ha solicitado por privado
Gracias y felicidades por este genial bot

**Comment by duhow** [comment]
No, pero está pensado para el futuro. Si el grupo es muy grande, el mensaje será muy grande y no se enviará, así que tengo que planificar bien como montar esto...

**Comment by duhow** [comment]
Por cierto, en un *canal* no se puede por límites de Telegram. En un grupo, sí.
