### ISSUE TITLE
¿Como desplegar el bot?

### ISSUE THREAD

**Issue by marcroga** [duhow/ProfesorOak#378]
Buenos días,

Agradecería ayuda para desplegar el bot.

Saludos

**Comment by JoseLSegura** [comment]
Justo eso mismo he preguntado yo aquí https://github.com/duhow/ProfesorOak/issues/377

**Comment by marcroga** [comment]
Déjame tu telegram y hablamos

**Comment by JoseLSegura** [comment]
jllk2

**Comment by roger93** [comment]
yo también estoy interesado @RogerGis
