### ISSUE TITLE
[IDEA] Pole

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#39]
Hacer la pole de Forocoches en plan casero. Contar una vez por usuario en todos los grupos, pero sólo uno por grupo.

**Comment by RussianEngineer** [comment]
Y hacer un ranking de quien hace mas poles de toda españa

**Comment by duhow** [comment]
Obviamente el ranking va incluido ;)

**Comment by duhow** [comment]
En parte va implementada. Queda guardar resultados en DB.

**Comment by duhow** [comment]
Falta el Ranking.

**Comment by duhow** [comment]
Creo que esto de momento se puede cerrar.
