### ISSUE TITLE
[IDEA] Multilenguaje

### ISSUE THREAD

**Issue by barreeeiroo** [duhow/ProfesorOak#43]
Hacer que el bot sea multilenguaje

Como hacerlo? Pues muy fácil:
Se pasan todas las strings a un .json, y se crean múltiples .json con diferentes idiomas, y luego en el bot se crea un comando en diferentes lenguajes en el que tu le envies tu idioma preferido y todos los mensajes que tu solicites vayan en ese idioma

**Comment by duhow** [comment]
Las respuestas si, pero el hecho de reconocer los grupos de palabras puede variar de cara a múltiples idiomas... Es muy complicado :(

**Comment by barreeeiroo** [comment]
Digo solo las respuestas en un futuro cercano, alomejor cuando el bot este pulido, se podría hacer que detecte el idioma del grupo

**Comment by duhow** [comment]
De que sirve responder en francés o inglés si le tienes que hablar en español? XD
Según el sistema de palabras está puesto, es complicado, y puede variar mucho la condición de un idioma a otro...

**Comment by barreeeiroo** [comment]
Pero se puede poner los comandos en diferentes idiomas

**Comment by duhow** [comment]
Vuelvo a insistir: el multilenguaje de respuesta puede ser fácil de poner, pero los comandos (que en su gran mayoría no serán comandos, si no FRASES) no siempre se escriben gramaticalmente igual, y puede dar pie a más líneas de código, con un orden específico para ese idioma.

La estructura que tiene ahora mismo el bot está pensada para grupos de palabras en español, y de entrada la DB será de España (o variante de habla hispánica - México, etc).

Asi pues, esto se queda como pendiente de cara al futuro, pero de prioridad baja. Ahora mismo interesa desarrollar todas las funciones, antes de meter idiomas...

**Comment by barreeeiroo** [comment]
É verdá, eso no lo había pensado, pero alomejor hay alguna API o bot que
reconozca palabras gramaticalmente no correctas
Puedes cerrar este issue si quieres, que llevaria bastante tiempo
