### ISSUE TITLE
[IDEA] API HTTP

### ISSUE THREAD

**Issue by barreeeiroo** [duhow/ProfesorOak#51]
Es una idea que se podría hacer si el proyecto se hace bastante grande: hacer una web del proyecto en la que se pudiese consultar algunas cosas del bot

**Comment by duhow** [comment]
Habrá sección API más adelante si sale bien, para la info de los jugadores. Lo que es Pokedex y demás va a cargo de otros, como pokeapi.co por ejemplo.

**Comment by barreeeiroo** [comment]
Perf
