### ISSUE TITLE
[IDEA] Analytics Tracking

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#55]
Para saber el uso (y abuso) de comandos, implementar modelo GA PHP server-side y hacer seguimiento de los comandos utilizados de forma anónima.

Valorar si también se debe especificar la frase utilizada o no, según la configuración que se pueda hacer.

Ejemplo tracking: Acción -> Evolución, Valor -> Charmander

**Comment by barreeeiroo** [comment]
Pero a que te refieres:

- A implementar Google Analytics para saber el uso del bot
- A implementar un sistema anti sobrecarga 
- A hacer un registro de todas las solicitudes, respuestas y comandos

**Comment by duhow** [comment]
Básicamente para saber el uso del bot, tener una idea de como la gente lo usa y poder mejorarlo con la información (no identificativa) que pueda utilizar para ello 😊
