### ISSUE TITLE
[IDEA] Automatizar descubrimiento de versión

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#60]
Conseguir API o algo para saber la información de apps publicadas en Play Store o Apple, y de ahí comprobar la fecha de actualización. Si es recién de 3 días, avisar.

**Comment by SKillusion** [comment]
Se puede hacer parseando periódicamente las paginas de Play y App Store, tengo un script de Python que hace eso, podré traducirlo a PHP.
