### ISSUE TITLE
[IDEA] Tabla de los huevos

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#62]
Si, suena ofensivo a la par que cómico, pero me refiero a la imagen de los Pokemon que pueden eclosionar de los huevos.

**Comment by Rapejim** [comment]
Incluso algo igual para los niveles y sus recompensas...
(si no está abrimos issue con la IDEA)

**Comment by duhow** [comment]
@Rapejim si, mejor abre uno nuevo. Separado por funciones mejor...

**Comment by Rapejim** [comment]
Ok, era por saber si no estaba, para abrirlo.
