### ISSUE TITLE
[IDEA] Calculo de los IVs de un Pokemon

### ISSUE THREAD

**Issue by rubenuno** [duhow/ProfesorOak#64]
Al teclear "calcular IV" profesor Oak mostrará el formato del comando que sería el siguiente:
`<pokemon> <CP> <HP> <Dust> <Powered>`
y el profesor Oak contestará con un valor máximo, mínimo y la media.
Nota: encontre este proyecto de Goatslacker  que igual nos puede ser útil. https://github.com/goatslacker/pokemon-go-iv-calculator

**Comment by RussianEngineer** [comment]
La idea de hacerlo por screenshot estaba tambien muy bien pensada

**Comment by duhow** [comment]
Pues ya puedes ponerte a investigar sobre OCR... XD

**Comment by RussianEngineer** [comment]
https://github.com/thiagoalessio/tesseract-ocr-for-php

**Comment by NatiSP** [comment]
https://gist.github.com/anonymous/540700108cf0f051e11f70273e9e2590

**Comment by barreeeiroo** [comment]
Puedo implementar yo el OCR
