### ISSUE TITLE
[IDEA] Mención 

### ISSUE THREAD

**Issue by barreeeiroo** [duhow/ProfesorOak#65]
Hacer que el bot sólo funcione cuando se le menciona, para que no envíe mensajes al azar o sin necesidad.

Ejemplo: @ProfesorOak_Bot Debilidad de Pikachu

**Comment by duhow** [comment]
La intención del bot es que conteste independientemente de a quien pregunte, porque por ejemplo para jugadores nuevos que aún no lo conozcan, se darán cuenta de que también pueden interactuar con él.

Entiendo que esto lo dices por el hecho de que a veces responde cuando no le toca, por coincidir en las frases de "pregunta", y en esto haremos hincapié para dejarlo lo más clavado y preciso posible.

No obstante, marco la idea como posible de cara a un futuro, con investigación pendiente, para poder desarrollar la misma función pero "sin lectura de mensajes" (ya que algunos usuarios temen por su privacidad, a pesar de que no hay peligro ninguno - excusas y follones que montan algunos...). Bien es cierto que con eso, algunas funciones es posible que se pierdan, pero insisto que esto requiere mirarlo con detalle. ;)

**Comment by Rapejim** [comment]
Como dijo noseque filosofo, la virtud está en el termino medio, xD.
Es decir, eso de tener que mencionarle con su alias, queda algo menos estético y no va del todo con el estilo free-commands del profe, por tanto y si tienes que "referirte a el" como Profe o como Oak:

- Debilidad de Pikachu aquí
(no responde)
- Profe debilidad de Pikachu aquí
(el profe responde)

Aunque por otro lado, si la gente ya le cuesta poner el simple "aquí" o el lógico "de"...
jejeje
