### ISSUE TITLE
[IDEA] Parsear coordenadas a ubicación

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#66]
Si se envían coordenadas en tipo:
- 44.1334, 2.322
- 7.121;6.3281

O en otros tipos, interpretar los dos dígitos con regex y enviar ubicación.

**Comment by SKillusion** [comment]
Aquí tengo el regex:
```php
    preg_match("/(\d+.\d+)[,;]\s?(\d+.\d+)/", $input_line, $output_array);
```

Aquí una [muestra en directo](http://www.phpliveregex.com/p/gIb)
