### ISSUE TITLE
[JUEGO] Ruleta rusa

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#7]
- Recarga / Gira el tambor. Genera número entre 1 y 6 que se guardará en el grupo.
- Dispara. El número sube 1, y si la bala es 6, dispara y la persona muere.

Agregar dificultad modo fácil: si NO está el modo fácil activo, si una persona muere, sera kickeada o baneada del grupo por el bot.

**Comment by HorusGoul** [comment]
Esto puede ser el mejor método para cuando un usuario incumpla las reglas de un grupo.

**Comment by duhow** [comment]
Buen apunte, aunque eso también es cosa del grupo... XD
