### ISSUE TITLE
[IDEA] OCR

### ISSUE THREAD

**Issue by barreeeiroo** [duhow/ProfesorOak#71]
Implementar reconocimiento por OCR de capturas del perfil de los Pokemons, indicando datos como CP, Caramelos, PolvoEstelar, etc.
Yo se implementarlo por si necesitas ayuda y quieres hacerlo

**Comment by duhow** [comment]
Hombre, por supuesto que iría bien! Todo tuyo, comunica cualquier avance que se pueda hacer

**Comment by barreeeiroo** [comment]
Okey, miro y te comento si es posible hacerlo en PHP.
Montaré un bot de prueba para ir probando cosas

**Comment by RussianEngineer** [comment]
#19 y tambien mirate los comentarios de #64

**Comment by barreeeiroo** [comment]
Pues se puede hacer y yo me puedo encargar de la parte de OCR @RussianEngineer

**Comment by RussianEngineer** [comment]
@barreeeiroo habla con david que el es quien controla ;)

**Comment by duhow** [comment]
Hay progreso al respecto desde el 310934a8ef97feda642f5ac2fab3565add54866c, pero el tema de reconocer los Pokémon es complicado, sobretodo por el fondo dinámico de bioma de los Pokémon / texto blanco, etc.
Se abrirá otro issue con peticiones detalladas del OCR.
