### ISSUE TITLE
[IDEA] Acortador de links

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#74]
Comando _acorta http://www.google.es_ devolverá una URL goo.gl .

Incluye la posibilidad de acortar URL en reply, buscando en total del mensaje sólo 1 o bien si el mensaje en si es la URL.

API o forma de poder enviar la petición?

**Comment by egarrod** [comment]
Tenia por ahi una clase que lo hacia, le tenias que poner tu code y tal de la api de google previamente. Te paso el code de la clase a ver si te sirve era super simple.

(No me deja subir .php xD)
[googl.php.txt](https://github.com/duhow/ProfesorOak/files/409405/googl.php.txt)

Y para llamar:

<?php
$api = new GoogleURL('CLAVE_API');
//ver url acortandola
echo $api->encode('http://pagina-a-acortar');
//ver url real
echo $api->decode('http://goo.gl/mbMv2X');
?>

A ver si te sirve!

**Comment by duhow** [comment]
Creo que voy a trabajar con bitly, menos rollos de Google...
https://davidwalsh.name/bitly-api-php
