### ISSUE TITLE
[IDEA] Tabla de recompensas por Nivel

### ISSUE THREAD

**Issue by Rapejim** [duhow/ProfesorOak#77]
Responder al entrenador que pida la tabla de recompensas por nivel.
Puede ser en global (como tabla en sí) o por nivel (que se obtiene al subir a X nivel).

**Comment by duhow** [comment]
Oki. Varias frases para activar la respuesta?

**Comment by ChupaCabritas** [comment]
Muestrame las recompensas de $entrenador

**Comment by RussianEngineer** [comment]
Cual es la recompensa por subir al Lvl X? 
Que me dan si subo al LX?
Cuales son las recompensas por subir de lvl?

**Comment by duhow** [comment]
Qué se consigue al nivel LX?

**Comment by RussianEngineer** [comment]
Tambien podria responder preguntas tipo: a que lv se desbloquean las Ultraballs? O los max revivir etc...

**Comment by ArconFly689** [comment]
[Nivel en PKMGO.txt](https://github.com/duhow/ProfesorOak/files/430730/Nivel.en.PKMGO.txt)

**Comment by SKillusion** [comment]
Tabla convertida: [niveles.csv.txt](https://github.com/duhow/ProfesorOak/files/433586/niveles.csv.txt)

**Comment by duhow** [comment]
De acuerdo, pues la estructura de items se queda [en el siguiente formato](https://github.com/duhow/ProfesorOak/files/437865/rewards.csv.txt)
