### ISSUE TITLE
[CAMBIO] Responder "citando" a quien responde

### ISSUE THREAD

**Issue by Rapejim** [duhow/ProfesorOak#78]
Cuando en un grupo hay mucha gente y por tanto escribiendo muchas lineas de seguido, se hace dificil saber a que ha respondido el profe, por tanto, cuando interviene el profe, que lo haga citando el mensajes al que está respondiendo.

Esto tambien ayudará a quien no sepa usarlo a saber como irle hablando al profe para que responda a sus inquietudes.

**Comment by duhow** [comment]
Lo de la cita lo tengo en algunas funciones, no en todas, porque representa hasta una carga visual (el mensaje en Telegram se ve más grande).

Dime algunos ejemplos que consideres que falten?

**Comment by Rapejim** [comment]
A mi personalmente las debilidades de tipo (bicho, electrico, ,,,) me parece que si no estas estricamente atento al chat, puede que no te enteres a quien esta respondiendo:
![image](https://cloud.githubusercontent.com/assets/7972545/17465238/736b03be-5cf2-11e6-8d6d-27c0a7ee5718.png)

**Comment by duhow** [comment]
Para no poner el reply, a pesar de que lo estoy pensando... voy a poner el titulo de la debilidad y listo, así queda más claro para las dos cosas :+1:
