### ISSUE TITLE
[IDEA] Es Admin?

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#80]
Reply a mensaje y decir si es Admin del grupo o no.

**Comment by Rapejim** [comment]
Creo que sería mejor poder preguntarle al profe directamente quien es el admin y este lo responda.
Sino puedo preguntarle sobre 100 usuarios "este es admin?" y "este es admin?" hasta que dé con el admin...

**Comment by Rapejim** [comment]
((no sabia que existía ese comando))

La gracia es pedirle un chiste puntualmente, no pedirle 20 chistes seguidos la misma persona... ya sabemos como es la gente, jajaja.
