### ISSUE TITLE
[CAMBIO] Tira el dado

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#81]
Agrega *Lanza el dado*.

**Comment by MrCritico** [comment]
¿Que puede utilidad puede tener en el Profesor?

**Comment by duhow** [comment]
Es jokes, tio... XD
Además, hay gente que juega al azar para tomar decisiones, no? Pues eso ;)

**Comment by Rapejim** [comment]
Y añadirle el numero de caras del dado?
- _Lanza/Tira el dado de 6_
- _Lanza/Tira el dado de 10_
- _Lanza/Tira el dado de 4_

**Comment by duhow** [comment]
Cualquier contenido de "cara o cruz" ya salta el joke. En cualquier caso, te cojo lo de los números para mejora más adelante, esto es de una palabra puntual. :tongue:
