### ISSUE TITLE
[IDEA] Identificación obligatoria

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#84]
Agregar a todos los usuarios nuevos que no estén registrados en una tabla aparte y si en 24 horas no se han registrado con su color correspondiente kickear los o bannear los del grupo

**Comment by Rapejim** [comment]
Creo que antes del kick/ban debería preceder un aviso o algo, no?

**Comment by duhow** [comment]
Queda el contador de tiempo de inactividad basado en mensajes.
Conforme la gente vaya hablando, fijarse en la hora, y si pasa del límite, ejecutar el Kick.
