### ISSUE TITLE
[IDEA] Imagen tabla de ataques

### ISSUE THREAD

**Issue by duhow** [duhow/ProfesorOak#9]
Del #8 Mostrar la tabla de ataques y debilidades.

**Comment by RussianEngineer** [comment]
Tambien podria sugerir ataques para vencer ciertos pokemon cuando alguien le pregunte debilidad de...

**Comment by duhow** [comment]
La lista de ataques podría ser muy grande, pero irá en compensación con otra cosa aparte.

**Comment by RussianEngineer** [comment]
Podria pasarte un link con los ataques para optimizar espacio.

**Comment by duhow** [comment]
Se sumará la info al #23.
