### ISSUE TITLE
[BUG] Oak detecta comandos cuando forman parte de palabras más largas

### ISSUE THREAD

**Issue by SKillusion** [duhow/ProfesorOak#91]
Oak responde a disparate porque contiene "dispara", puertazo porque contiene "puerta" etc.

**Comment by duhow** [comment]
Toca ya trabajar con la [API Telegram](https://github.com/duhow/CodeIgniter-Telegram)...
Cambiar función **receive** por **text_contains** y crear otra para buscar palabras exactas.
De hecho posiblemente harán falta dos funciones....

**Comment by barreeeiroo** [comment]
Pero se puede intentar hacer como se puso en el issue #65
